-- workspace
CREATE TABLE `workspace` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `uid` VARCHAR(256) NOT NULL UNIQUE,
  `creator_id` INT NOT NULL,
  `title` VARCHAR(256) NOT NULL,
  `created_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- workspace_folder
CREATE TABLE `workspace_folder` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `workspace_id` INT NOT NULL,
  `path` VARCHAR(512) NOT NULL,
  `created_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(`workspace_id`, `path`)
);
